// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Teamwork.CRM.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// activityResponse
    /// </summary>
    public partial class ActivitiesjsonCreatedResponse
    {
        /// <summary>
        /// Initializes a new instance of the ActivitiesjsonCreatedResponse
        /// class.
        /// </summary>
        public ActivitiesjsonCreatedResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ActivitiesjsonCreatedResponse
        /// class.
        /// </summary>
        /// <param name="activity">Activity</param>
        /// <param name="included">Included</param>
        public ActivitiesjsonCreatedResponse(ActivitiesjsonCreatedResponseActivity activity = default(ActivitiesjsonCreatedResponseActivity), object included = default(object))
        {
            Activity = activity;
            Included = included;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets activity
        /// </summary>
        /// <remarks>
        /// Activity represents an activity in the CRM system.
        /// </remarks>
        [JsonProperty(PropertyName = "activity")]
        public ActivitiesjsonCreatedResponseActivity Activity { get; set; }

        /// <summary>
        /// Gets or sets included
        /// </summary>
        /// <remarks>
        /// Included contains all the side-loaded data of a response.
        /// See [including related
        /// entities](https://crmdev-teamwork.docs.stoplight.io/documentation/general/related-entities).
        /// </remarks>
        [JsonProperty(PropertyName = "included")]
        public object Included { get; set; }

    }
}
