// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Teamwork.CRM.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// CustomFieldValue
    /// </summary>
    /// <remarks>
    /// CustomFieldValue represents a custom field and its value for an entity.
    /// </remarks>
    public partial class CompaniesjsonOKResponseCompaniesItemCustomItem
    {
        /// <summary>
        /// Initializes a new instance of the
        /// CompaniesjsonOKResponseCompaniesItemCustomItem class.
        /// </summary>
        public CompaniesjsonOKResponseCompaniesItemCustomItem()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// CompaniesjsonOKResponseCompaniesItemCustomItem class.
        /// </summary>
        /// <param name="changed">set to true on UnmarshalJSON if value
        /// changed</param>
        /// <param name="createdBy">[Resource identifier
        /// object](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#relationships)
        /// which describes a relationship to another entity.</param>
        /// <param name="deletedBy">[Resource identifier
        /// object](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#relationships)
        /// which describes a relationship to another entity.</param>
        /// <param name="updatedBy">[Resource identifier
        /// object](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#relationships)
        /// which describes a relationship to another entity.</param>
        public CompaniesjsonOKResponseCompaniesItemCustomItem(bool? changed = default(bool?), int? fieldID = default(int?), string key = default(string), string type = default(string), string val = default(string), System.DateTime? createdAt = default(System.DateTime?), CompaniesjsonOKResponseCompaniesItemCustomItemCreatedBy createdBy = default(CompaniesjsonOKResponseCompaniesItemCustomItemCreatedBy), System.DateTime? deletedAt = default(System.DateTime?), CompaniesjsonOKResponseCompaniesItemCustomItemDeletedBy deletedBy = default(CompaniesjsonOKResponseCompaniesItemCustomItemDeletedBy), System.DateTime? updatedAt = default(System.DateTime?), CompaniesjsonOKResponseCompaniesItemCustomItemUpdatedBy updatedBy = default(CompaniesjsonOKResponseCompaniesItemCustomItemUpdatedBy), int? updatedSourceId = default(int?))
        {
            Changed = changed;
            FieldID = fieldID;
            Key = key;
            Type = type;
            Val = val;
            CreatedAt = createdAt;
            CreatedBy = createdBy;
            DeletedAt = deletedAt;
            DeletedBy = deletedBy;
            UpdatedAt = updatedAt;
            UpdatedBy = updatedBy;
            UpdatedSourceId = updatedSourceId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets set to true on UnmarshalJSON if value changed
        /// </summary>
        [JsonProperty(PropertyName = "Changed")]
        public bool? Changed { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FieldID")]
        public int? FieldID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Key")]
        public string Key { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Type")]
        public string Type { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Val")]
        public string Val { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "createdAt")]
        public System.DateTime? CreatedAt { get; set; }

        /// <summary>
        /// Gets or sets [Resource identifier
        /// object](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#relationships)
        /// which describes a relationship to another entity.
        /// </summary>
        [JsonProperty(PropertyName = "createdBy")]
        public CompaniesjsonOKResponseCompaniesItemCustomItemCreatedBy CreatedBy { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "deletedAt")]
        public System.DateTime? DeletedAt { get; set; }

        /// <summary>
        /// Gets or sets [Resource identifier
        /// object](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#relationships)
        /// which describes a relationship to another entity.
        /// </summary>
        [JsonProperty(PropertyName = "deletedBy")]
        public CompaniesjsonOKResponseCompaniesItemCustomItemDeletedBy DeletedBy { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "updatedAt")]
        public System.DateTime? UpdatedAt { get; set; }

        /// <summary>
        /// Gets or sets [Resource identifier
        /// object](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#relationships)
        /// which describes a relationship to another entity.
        /// </summary>
        [JsonProperty(PropertyName = "updatedBy")]
        public CompaniesjsonOKResponseCompaniesItemCustomItemUpdatedBy UpdatedBy { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "updatedSourceId")]
        public int? UpdatedSourceId { get; set; }

    }
}
