// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Teamwork.CRM.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Company
    /// </summary>
    /// <remarks>
    /// Company represents a company in the CRM system.
    /// </remarks>
    public partial class CompaniesjsonCreatedResponseCompany
    {
        /// <summary>
        /// Initializes a new instance of the
        /// CompaniesjsonCreatedResponseCompany class.
        /// </summary>
        public CompaniesjsonCreatedResponseCompany()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// CompaniesjsonCreatedResponseCompany class.
        /// </summary>
        /// <param name="avatar">[Resource identifier
        /// object](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#relationships)
        /// which describes a relationship to another entity.</param>
        /// <param name="contacts">[To-many relationship
        /// array](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#to-many-relationships)
        /// which describes a list of resource identifier objects.</param>
        /// <param name="contactsCount">Number of contacts connected.</param>
        /// <param name="country">[Resource identifier
        /// object](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#relationships)
        /// which describes a relationship to another entity.</param>
        /// <param name="createdBy">[Resource identifier
        /// object](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#relationships)
        /// which describes a relationship to another entity.</param>
        /// <param name="custom">Custom fields of the company.</param>
        /// <param name="deletedBy">[Resource identifier
        /// object](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#relationships)
        /// which describes a relationship to another entity.</param>
        /// <param name="owner">[Resource identifier
        /// object](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#relationships)
        /// which describes a relationship to another entity.</param>
        /// <param name="timezone">[Resource identifier
        /// object](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#relationships)
        /// which describes a relationship to another entity.</param>
        /// <param name="updatedBy">[Resource identifier
        /// object](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#relationships)
        /// which describes a relationship to another entity.</param>
        /// <param name="website">Companies website URL.</param>
        public CompaniesjsonCreatedResponseCompany(string addressLine1 = default(string), string addressLine2 = default(string), CompaniesjsonCreatedResponseCompanyAvatar avatar = default(CompaniesjsonCreatedResponseCompanyAvatar), string city = default(string), IList<CompaniesjsonCreatedResponseCompanyContactsItem> contacts = default(IList<CompaniesjsonCreatedResponseCompanyContactsItem>), int? contactsCount = default(int?), CompaniesjsonCreatedResponseCompanyCountry country = default(CompaniesjsonCreatedResponseCompanyCountry), System.DateTime? createdAt = default(System.DateTime?), CompaniesjsonCreatedResponseCompanyCreatedBy createdBy = default(CompaniesjsonCreatedResponseCompanyCreatedBy), IList<CompaniesjsonCreatedResponseCompanyCustomItem> custom = default(IList<CompaniesjsonCreatedResponseCompanyCustomItem>), System.DateTime? deletedAt = default(System.DateTime?), CompaniesjsonCreatedResponseCompanyDeletedBy deletedBy = default(CompaniesjsonCreatedResponseCompanyDeletedBy), IList<CompaniesjsonCreatedResponseCompanyEmailAddressesItem> emailAddresses = default(IList<CompaniesjsonCreatedResponseCompanyEmailAddressesItem>), int? hubId = default(int?), int? id = default(int?), string name = default(string), CompaniesjsonCreatedResponseCompanyOwner owner = default(CompaniesjsonCreatedResponseCompanyOwner), CompaniesjsonCreatedResponseCompanyPhoneNumbers phoneNumbers = default(CompaniesjsonCreatedResponseCompanyPhoneNumbers), string stateOrCounty = default(string), CompaniesjsonCreatedResponseCompanyTimezone timezone = default(CompaniesjsonCreatedResponseCompanyTimezone), System.DateTime? updatedAt = default(System.DateTime?), CompaniesjsonCreatedResponseCompanyUpdatedBy updatedBy = default(CompaniesjsonCreatedResponseCompanyUpdatedBy), int? updatedSourceId = default(int?), string website = default(string), string zipcode = default(string))
        {
            AddressLine1 = addressLine1;
            AddressLine2 = addressLine2;
            Avatar = avatar;
            City = city;
            Contacts = contacts;
            ContactsCount = contactsCount;
            Country = country;
            CreatedAt = createdAt;
            CreatedBy = createdBy;
            Custom = custom;
            DeletedAt = deletedAt;
            DeletedBy = deletedBy;
            EmailAddresses = emailAddresses;
            HubId = hubId;
            Id = id;
            Name = name;
            Owner = owner;
            PhoneNumbers = phoneNumbers;
            StateOrCounty = stateOrCounty;
            Timezone = timezone;
            UpdatedAt = updatedAt;
            UpdatedBy = updatedBy;
            UpdatedSourceId = updatedSourceId;
            Website = website;
            Zipcode = zipcode;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "addressLine1")]
        public string AddressLine1 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "addressLine2")]
        public string AddressLine2 { get; set; }

        /// <summary>
        /// Gets or sets [Resource identifier
        /// object](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#relationships)
        /// which describes a relationship to another entity.
        /// </summary>
        [JsonProperty(PropertyName = "avatar")]
        public CompaniesjsonCreatedResponseCompanyAvatar Avatar { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "city")]
        public string City { get; set; }

        /// <summary>
        /// Gets or sets [To-many relationship
        /// array](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#to-many-relationships)
        /// which describes a list of resource identifier objects.
        /// </summary>
        [JsonProperty(PropertyName = "contacts")]
        public IList<CompaniesjsonCreatedResponseCompanyContactsItem> Contacts { get; set; }

        /// <summary>
        /// Gets or sets number of contacts connected.
        /// </summary>
        [JsonProperty(PropertyName = "contactsCount")]
        public int? ContactsCount { get; set; }

        /// <summary>
        /// Gets or sets [Resource identifier
        /// object](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#relationships)
        /// which describes a relationship to another entity.
        /// </summary>
        [JsonProperty(PropertyName = "country")]
        public CompaniesjsonCreatedResponseCompanyCountry Country { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "createdAt")]
        public System.DateTime? CreatedAt { get; set; }

        /// <summary>
        /// Gets or sets [Resource identifier
        /// object](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#relationships)
        /// which describes a relationship to another entity.
        /// </summary>
        [JsonProperty(PropertyName = "createdBy")]
        public CompaniesjsonCreatedResponseCompanyCreatedBy CreatedBy { get; set; }

        /// <summary>
        /// Gets or sets custom fields of the company.
        /// </summary>
        [JsonProperty(PropertyName = "custom")]
        public IList<CompaniesjsonCreatedResponseCompanyCustomItem> Custom { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "deletedAt")]
        public System.DateTime? DeletedAt { get; set; }

        /// <summary>
        /// Gets or sets [Resource identifier
        /// object](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#relationships)
        /// which describes a relationship to another entity.
        /// </summary>
        [JsonProperty(PropertyName = "deletedBy")]
        public CompaniesjsonCreatedResponseCompanyDeletedBy DeletedBy { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "emailAddresses")]
        public IList<CompaniesjsonCreatedResponseCompanyEmailAddressesItem> EmailAddresses { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "hubId")]
        public int? HubId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets [Resource identifier
        /// object](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#relationships)
        /// which describes a relationship to another entity.
        /// </summary>
        [JsonProperty(PropertyName = "owner")]
        public CompaniesjsonCreatedResponseCompanyOwner Owner { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "phoneNumbers")]
        public CompaniesjsonCreatedResponseCompanyPhoneNumbers PhoneNumbers { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "stateOrCounty")]
        public string StateOrCounty { get; set; }

        /// <summary>
        /// Gets or sets [Resource identifier
        /// object](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#relationships)
        /// which describes a relationship to another entity.
        /// </summary>
        [JsonProperty(PropertyName = "timezone")]
        public CompaniesjsonCreatedResponseCompanyTimezone Timezone { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "updatedAt")]
        public System.DateTime? UpdatedAt { get; set; }

        /// <summary>
        /// Gets or sets [Resource identifier
        /// object](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#relationships)
        /// which describes a relationship to another entity.
        /// </summary>
        [JsonProperty(PropertyName = "updatedBy")]
        public CompaniesjsonCreatedResponseCompanyUpdatedBy UpdatedBy { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "updatedSourceId")]
        public int? UpdatedSourceId { get; set; }

        /// <summary>
        /// Gets or sets companies website URL.
        /// </summary>
        [JsonProperty(PropertyName = "website")]
        public string Website { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "zipcode")]
        public string Zipcode { get; set; }

    }
}
