// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Teamwork.CRM.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// contactsResponse
    /// </summary>
    public partial class ContactsjsonOKResponse
    {
        /// <summary>
        /// Initializes a new instance of the ContactsjsonOKResponse class.
        /// </summary>
        public ContactsjsonOKResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ContactsjsonOKResponse class.
        /// </summary>
        /// <param name="included">Included</param>
        /// <param name="meta">ResponseMeta</param>
        public ContactsjsonOKResponse(IList<ContactsjsonOKResponseContactsItem> contacts = default(IList<ContactsjsonOKResponseContactsItem>), object included = default(object), ContactsjsonOKResponseMeta meta = default(ContactsjsonOKResponseMeta))
        {
            Contacts = contacts;
            Included = included;
            Meta = meta;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "contacts")]
        public IList<ContactsjsonOKResponseContactsItem> Contacts { get; set; }

        /// <summary>
        /// Gets or sets included
        /// </summary>
        /// <remarks>
        /// Included contains all the side-loaded data of a response.
        /// See [including related
        /// entities](https://crmdev-teamwork.docs.stoplight.io/documentation/general/related-entities).
        /// </remarks>
        [JsonProperty(PropertyName = "included")]
        public object Included { get; set; }

        /// <summary>
        /// Gets or sets responseMeta
        /// </summary>
        /// <remarks>
        /// ResponseMeta contains common meta data.
        /// </remarks>
        [JsonProperty(PropertyName = "meta")]
        public ContactsjsonOKResponseMeta Meta { get; set; }

    }
}
