// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Teamwork.CRM.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Timezone
    /// </summary>
    /// <remarks>
    /// Timezone in CRM
    /// </remarks>
    public partial class CrmcoreTimezone
    {
        /// <summary>
        /// Initializes a new instance of the CrmcoreTimezone class.
        /// </summary>
        public CrmcoreTimezone()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CrmcoreTimezone class.
        /// </summary>
        public CrmcoreTimezone(int? id = default(int?), string name = default(string), int? offsetMinutes = default(int?), string reference = default(string))
        {
            Id = id;
            Name = name;
            OffsetMinutes = offsetMinutes;
            Reference = reference;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "offsetMinutes")]
        public int? OffsetMinutes { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "reference")]
        public string Reference { get; set; }

    }
}
