// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Teamwork.CRM.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// FileUploadRequestFile
    /// </summary>
    /// <remarks>
    /// FileUploadRequestFile is a single file in a FileUploadRequest.
    /// </remarks>
    public partial class CrmcoreFileUploadRequestFilesItem
    {
        /// <summary>
        /// Initializes a new instance of the CrmcoreFileUploadRequestFilesItem
        /// class.
        /// </summary>
        public CrmcoreFileUploadRequestFilesItem()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CrmcoreFileUploadRequestFilesItem
        /// class.
        /// </summary>
        public CrmcoreFileUploadRequestFilesItem(string description = default(string), bool? isAvatar = default(bool?), string tempId = default(string))
        {
            Description = description;
            IsAvatar = isAvatar;
            TempId = tempId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isAvatar")]
        public bool? IsAvatar { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tempId")]
        public string TempId { get; set; }

    }
}
