// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Teamwork.CRM.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// OvertimePoint
    /// </summary>
    /// <remarks>
    /// OvertimePoint fields
    /// </remarks>
    public partial class CrmcoreOvertimeReportDataPointsItem
    {
        /// <summary>
        /// Initializes a new instance of the
        /// CrmcoreOvertimeReportDataPointsItem class.
        /// </summary>
        public CrmcoreOvertimeReportDataPointsItem()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// CrmcoreOvertimeReportDataPointsItem class.
        /// </summary>
        /// <param name="date">timestamp in seconds</param>
        public CrmcoreOvertimeReportDataPointsItem(int? date = default(int?), double? value = default(double?))
        {
            Date = date;
            Value = value;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets timestamp in seconds
        /// </summary>
        [JsonProperty(PropertyName = "date")]
        public int? Date { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public double? Value { get; set; }

    }
}
