// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Teamwork.CRM.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Phone
    /// </summary>
    /// <remarks>
    /// Phone is a phone number.
    /// </remarks>
    public partial class CrmcoreInstallationBillingPhone
    {
        /// <summary>
        /// Initializes a new instance of the CrmcoreInstallationBillingPhone
        /// class.
        /// </summary>
        public CrmcoreInstallationBillingPhone()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CrmcoreInstallationBillingPhone
        /// class.
        /// </summary>
        /// <param name="country">Country</param>
        public CrmcoreInstallationBillingPhone(CrmcoreInstallationBillingPhoneCountry country = default(CrmcoreInstallationBillingPhoneCountry), string extension = default(string), int? id = default(int?), string kind = default(string), string number = default(string))
        {
            Country = country;
            Extension = extension;
            Id = id;
            Kind = kind;
            Number = number;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets country
        /// </summary>
        /// <remarks>
        /// Country represents a country.
        /// </remarks>
        [JsonProperty(PropertyName = "country")]
        public CrmcoreInstallationBillingPhoneCountry Country { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "extension")]
        public string Extension { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "kind")]
        public string Kind { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "number")]
        public string Number { get; set; }

    }
}
