// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Teamwork.CRM.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// DealReportStatuses
    /// </summary>
    /// <remarks>
    /// DealReportStatuses fields.
    /// </remarks>
    public partial class CrmcoreDealReportWithIncludesDataItemStatuses
    {
        /// <summary>
        /// Initializes a new instance of the
        /// CrmcoreDealReportWithIncludesDataItemStatuses class.
        /// </summary>
        public CrmcoreDealReportWithIncludesDataItemStatuses()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// CrmcoreDealReportWithIncludesDataItemStatuses class.
        /// </summary>
        /// <param name="lost">DealReportStatus</param>
        /// <param name="open">DealReportStatus</param>
        /// <param name="won">DealReportStatus</param>
        public CrmcoreDealReportWithIncludesDataItemStatuses(CrmcoreDealReportWithIncludesDataItemStatusesLost lost = default(CrmcoreDealReportWithIncludesDataItemStatusesLost), CrmcoreDealReportWithIncludesDataItemStatusesOpen open = default(CrmcoreDealReportWithIncludesDataItemStatusesOpen), CrmcoreDealReportWithIncludesDataItemStatusesWon won = default(CrmcoreDealReportWithIncludesDataItemStatusesWon))
        {
            Lost = lost;
            Open = open;
            Won = won;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets dealReportStatus
        /// </summary>
        /// <remarks>
        /// DealReportStatus fields
        /// </remarks>
        [JsonProperty(PropertyName = "lost")]
        public CrmcoreDealReportWithIncludesDataItemStatusesLost Lost { get; set; }

        /// <summary>
        /// Gets or sets dealReportStatus
        /// </summary>
        /// <remarks>
        /// DealReportStatus fields
        /// </remarks>
        [JsonProperty(PropertyName = "open")]
        public CrmcoreDealReportWithIncludesDataItemStatusesOpen Open { get; set; }

        /// <summary>
        /// Gets or sets dealReportStatus
        /// </summary>
        /// <remarks>
        /// DealReportStatus fields
        /// </remarks>
        [JsonProperty(PropertyName = "won")]
        public CrmcoreDealReportWithIncludesDataItemStatusesWon Won { get; set; }

    }
}
