// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Teamwork.CRM.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Address
    /// </summary>
    /// <remarks>
    /// Address is a postal/real-life address.
    /// </remarks>
    public partial class CrmcoreInstallationBillingAddress
    {
        /// <summary>
        /// Initializes a new instance of the CrmcoreInstallationBillingAddress
        /// class.
        /// </summary>
        public CrmcoreInstallationBillingAddress()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CrmcoreInstallationBillingAddress
        /// class.
        /// </summary>
        /// <param name="country">Country</param>
        public CrmcoreInstallationBillingAddress(string city = default(string), CrmcoreInstallationBillingAddressCountry country = default(CrmcoreInstallationBillingAddressCountry), int? id = default(int?), string line1 = default(string), string line2 = default(string), string region = default(string), string zip = default(string))
        {
            City = city;
            Country = country;
            Id = id;
            Line1 = line1;
            Line2 = line2;
            Region = region;
            Zip = zip;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "city")]
        public string City { get; set; }

        /// <summary>
        /// Gets or sets country
        /// </summary>
        /// <remarks>
        /// Country represents a country.
        /// </remarks>
        [JsonProperty(PropertyName = "country")]
        public CrmcoreInstallationBillingAddressCountry Country { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "line1")]
        public string Line1 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "line2")]
        public string Line2 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "region")]
        public string Region { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "zip")]
        public string Zip { get; set; }

    }
}
