// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Teamwork.CRM.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// currenciesResponse
    /// </summary>
    public partial class CurrenciesjsonOKResponse
    {
        /// <summary>
        /// Initializes a new instance of the CurrenciesjsonOKResponse class.
        /// </summary>
        public CurrenciesjsonOKResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CurrenciesjsonOKResponse class.
        /// </summary>
        /// <param name="meta">ResponseMeta</param>
        public CurrenciesjsonOKResponse(IList<CurrenciesjsonOKResponseCurrenciesItem> currencies = default(IList<CurrenciesjsonOKResponseCurrenciesItem>), CurrenciesjsonOKResponseMeta meta = default(CurrenciesjsonOKResponseMeta))
        {
            Currencies = currencies;
            Meta = meta;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "currencies")]
        public IList<CurrenciesjsonOKResponseCurrenciesItem> Currencies { get; set; }

        /// <summary>
        /// Gets or sets responseMeta
        /// </summary>
        /// <remarks>
        /// ResponseMeta contains common meta data.
        /// </remarks>
        [JsonProperty(PropertyName = "meta")]
        public CurrenciesjsonOKResponseMeta Meta { get; set; }

    }
}
