// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Teamwork.CRM.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// customFiltersResponse
    /// </summary>
    public partial class CustomFiltersjsonOKResponse
    {
        /// <summary>
        /// Initializes a new instance of the CustomFiltersjsonOKResponse
        /// class.
        /// </summary>
        public CustomFiltersjsonOKResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CustomFiltersjsonOKResponse
        /// class.
        /// </summary>
        /// <param name="meta">ResponseMeta</param>
        public CustomFiltersjsonOKResponse(IList<CustomFiltersjsonOKResponseCustomFiltersItem> customFilters = default(IList<CustomFiltersjsonOKResponseCustomFiltersItem>), CustomFiltersjsonOKResponseMeta meta = default(CustomFiltersjsonOKResponseMeta))
        {
            CustomFilters = customFilters;
            Meta = meta;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "customFilters")]
        public IList<CustomFiltersjsonOKResponseCustomFiltersItem> CustomFilters { get; set; }

        /// <summary>
        /// Gets or sets responseMeta
        /// </summary>
        /// <remarks>
        /// ResponseMeta contains common meta data.
        /// </remarks>
        [JsonProperty(PropertyName = "meta")]
        public CustomFiltersjsonOKResponseMeta Meta { get; set; }

    }
}
