// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Teamwork.CRM.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// customFilterResponse
    /// </summary>
    public partial class CustomFiltersjsonCreatedResponse
    {
        /// <summary>
        /// Initializes a new instance of the CustomFiltersjsonCreatedResponse
        /// class.
        /// </summary>
        public CustomFiltersjsonCreatedResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CustomFiltersjsonCreatedResponse
        /// class.
        /// </summary>
        /// <param name="customFilter">CustomFilter</param>
        public CustomFiltersjsonCreatedResponse(CustomFiltersjsonCreatedResponseCustomFilter customFilter = default(CustomFiltersjsonCreatedResponseCustomFilter))
        {
            CustomFilter = customFilter;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets customFilter
        /// </summary>
        /// <remarks>
        /// CustomFilter is a custom field defined by a user.
        /// </remarks>
        [JsonProperty(PropertyName = "customFilter")]
        public CustomFiltersjsonCreatedResponseCustomFilter CustomFilter { get; set; }

    }
}
