// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Teamwork.CRM.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// CustomFilterColumn
    /// </summary>
    /// <remarks>
    /// CustomFilterColumn represents customer column for custom filter stored
    /// in the db.
    /// </remarks>
    public partial class CustomFiltersjsonOKResponseCustomFiltersItemColumnsItem
    {
        /// <summary>
        /// Initializes a new instance of the
        /// CustomFiltersjsonOKResponseCustomFiltersItemColumnsItem class.
        /// </summary>
        public CustomFiltersjsonOKResponseCustomFiltersItemColumnsItem()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// CustomFiltersjsonOKResponseCustomFiltersItemColumnsItem class.
        /// </summary>
        /// <param name="createdBy">[Resource identifier
        /// object](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#relationships)
        /// which describes a relationship to another entity.</param>
        /// <param name="deletedBy">[Resource identifier
        /// object](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#relationships)
        /// which describes a relationship to another entity.</param>
        /// <param name="updatedBy">[Resource identifier
        /// object](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#relationships)
        /// which describes a relationship to another entity.</param>
        public CustomFiltersjsonOKResponseCustomFiltersItemColumnsItem(string code = default(string), System.DateTime? createdAt = default(System.DateTime?), CustomFiltersjsonOKResponseCustomFiltersItemColumnsItemCreatedBy createdBy = default(CustomFiltersjsonOKResponseCustomFiltersItemColumnsItemCreatedBy), System.DateTime? deletedAt = default(System.DateTime?), CustomFiltersjsonOKResponseCustomFiltersItemColumnsItemDeletedBy deletedBy = default(CustomFiltersjsonOKResponseCustomFiltersItemColumnsItemDeletedBy), System.DateTime? updatedAt = default(System.DateTime?), CustomFiltersjsonOKResponseCustomFiltersItemColumnsItemUpdatedBy updatedBy = default(CustomFiltersjsonOKResponseCustomFiltersItemColumnsItemUpdatedBy), int? updatedSourceId = default(int?))
        {
            Code = code;
            CreatedAt = createdAt;
            CreatedBy = createdBy;
            DeletedAt = deletedAt;
            DeletedBy = deletedBy;
            UpdatedAt = updatedAt;
            UpdatedBy = updatedBy;
            UpdatedSourceId = updatedSourceId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "code")]
        public string Code { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "createdAt")]
        public System.DateTime? CreatedAt { get; set; }

        /// <summary>
        /// Gets or sets [Resource identifier
        /// object](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#relationships)
        /// which describes a relationship to another entity.
        /// </summary>
        [JsonProperty(PropertyName = "createdBy")]
        public CustomFiltersjsonOKResponseCustomFiltersItemColumnsItemCreatedBy CreatedBy { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "deletedAt")]
        public System.DateTime? DeletedAt { get; set; }

        /// <summary>
        /// Gets or sets [Resource identifier
        /// object](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#relationships)
        /// which describes a relationship to another entity.
        /// </summary>
        [JsonProperty(PropertyName = "deletedBy")]
        public CustomFiltersjsonOKResponseCustomFiltersItemColumnsItemDeletedBy DeletedBy { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "updatedAt")]
        public System.DateTime? UpdatedAt { get; set; }

        /// <summary>
        /// Gets or sets [Resource identifier
        /// object](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#relationships)
        /// which describes a relationship to another entity.
        /// </summary>
        [JsonProperty(PropertyName = "updatedBy")]
        public CustomFiltersjsonOKResponseCustomFiltersItemColumnsItemUpdatedBy UpdatedBy { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "updatedSourceId")]
        public int? UpdatedSourceId { get; set; }

    }
}
