// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Teamwork.CRM.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// File
    /// </summary>
    /// <remarks>
    /// File represents a uploaded file in the CRM system.
    /// </remarks>
    public partial class FilesjsonOKResponseFilesItem
    {
        /// <summary>
        /// Initializes a new instance of the FilesjsonOKResponseFilesItem
        /// class.
        /// </summary>
        public FilesjsonOKResponseFilesItem()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the FilesjsonOKResponseFilesItem
        /// class.
        /// </summary>
        /// <param name="createdBy">[Resource identifier
        /// object](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#relationships)
        /// which describes a relationship to another entity.</param>
        /// <param name="deletedBy">[Resource identifier
        /// object](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#relationships)
        /// which describes a relationship to another entity.</param>
        /// <param name="isAvatar">Defines if a file is used as an
        /// avatar</param>
        /// <param name="target">[Resource identifier
        /// object](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#relationships)
        /// which describes a relationship to another entity.</param>
        /// <param name="updatedBy">[Resource identifier
        /// object](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#relationships)
        /// which describes a relationship to another entity.</param>
        public FilesjsonOKResponseFilesItem(int? bytes = default(int?), System.DateTime? createdAt = default(System.DateTime?), FilesjsonOKResponseFilesItemCreatedBy createdBy = default(FilesjsonOKResponseFilesItemCreatedBy), System.DateTime? deletedAt = default(System.DateTime?), FilesjsonOKResponseFilesItemDeletedBy deletedBy = default(FilesjsonOKResponseFilesItemDeletedBy), string description = default(string), int? height = default(int?), int? id = default(int?), bool? isAvatar = default(bool?), string mimeType = default(string), string name = default(string), string path = default(string), FilesjsonOKResponseFilesItemTarget target = default(FilesjsonOKResponseFilesItemTarget), IList<FilesjsonOKResponseFilesItemThumbnailsItem> thumbnails = default(IList<FilesjsonOKResponseFilesItemThumbnailsItem>), System.DateTime? updatedAt = default(System.DateTime?), FilesjsonOKResponseFilesItemUpdatedBy updatedBy = default(FilesjsonOKResponseFilesItemUpdatedBy), int? updatedSourceId = default(int?), int? width = default(int?))
        {
            Bytes = bytes;
            CreatedAt = createdAt;
            CreatedBy = createdBy;
            DeletedAt = deletedAt;
            DeletedBy = deletedBy;
            Description = description;
            Height = height;
            Id = id;
            IsAvatar = isAvatar;
            MimeType = mimeType;
            Name = name;
            Path = path;
            Target = target;
            Thumbnails = thumbnails;
            UpdatedAt = updatedAt;
            UpdatedBy = updatedBy;
            UpdatedSourceId = updatedSourceId;
            Width = width;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "bytes")]
        public int? Bytes { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "createdAt")]
        public System.DateTime? CreatedAt { get; set; }

        /// <summary>
        /// Gets or sets [Resource identifier
        /// object](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#relationships)
        /// which describes a relationship to another entity.
        /// </summary>
        [JsonProperty(PropertyName = "createdBy")]
        public FilesjsonOKResponseFilesItemCreatedBy CreatedBy { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "deletedAt")]
        public System.DateTime? DeletedAt { get; set; }

        /// <summary>
        /// Gets or sets [Resource identifier
        /// object](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#relationships)
        /// which describes a relationship to another entity.
        /// </summary>
        [JsonProperty(PropertyName = "deletedBy")]
        public FilesjsonOKResponseFilesItemDeletedBy DeletedBy { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "height")]
        public int? Height { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int? Id { get; set; }

        /// <summary>
        /// Gets or sets defines if a file is used as an avatar
        /// </summary>
        [JsonProperty(PropertyName = "isAvatar")]
        public bool? IsAvatar { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "mimeType")]
        public string MimeType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "path")]
        public string Path { get; set; }

        /// <summary>
        /// Gets or sets [Resource identifier
        /// object](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#relationships)
        /// which describes a relationship to another entity.
        /// </summary>
        [JsonProperty(PropertyName = "target")]
        public FilesjsonOKResponseFilesItemTarget Target { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "thumbnails")]
        public IList<FilesjsonOKResponseFilesItemThumbnailsItem> Thumbnails { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "updatedAt")]
        public System.DateTime? UpdatedAt { get; set; }

        /// <summary>
        /// Gets or sets [Resource identifier
        /// object](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#relationships)
        /// which describes a relationship to another entity.
        /// </summary>
        [JsonProperty(PropertyName = "updatedBy")]
        public FilesjsonOKResponseFilesItemUpdatedBy UpdatedBy { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "updatedSourceId")]
        public int? UpdatedSourceId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "width")]
        public int? Width { get; set; }

    }
}
