// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Teamwork.CRM.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// createdFilesResponse
    /// </summary>
    public partial class FilesjsonCreatedResponse
    {
        /// <summary>
        /// Initializes a new instance of the FilesjsonCreatedResponse class.
        /// </summary>
        public FilesjsonCreatedResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the FilesjsonCreatedResponse class.
        /// </summary>
        public FilesjsonCreatedResponse(IList<FilesjsonCreatedResponseFilesItem> files = default(IList<FilesjsonCreatedResponseFilesItem>))
        {
            Files = files;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "files")]
        public IList<FilesjsonCreatedResponseFilesItem> Files { get; set; }

    }
}
