// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Teamwork.CRM.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// installationSettingsResponse
    /// </summary>
    public partial class IdjsonOKResponseModelModelModelModelModelModelModelModel
    {
        /// <summary>
        /// Initializes a new instance of the
        /// IdjsonOKResponseModelModelModelModelModelModelModelModel class.
        /// </summary>
        public IdjsonOKResponseModelModelModelModelModelModelModelModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// IdjsonOKResponseModelModelModelModelModelModelModelModel class.
        /// </summary>
        /// <param name="installationSettings">InstallationSettings</param>
        public IdjsonOKResponseModelModelModelModelModelModelModelModel(IdjsonOKResponseInstallationSettings installationSettings = default(IdjsonOKResponseInstallationSettings))
        {
            InstallationSettings = installationSettings;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets installationSettings
        /// </summary>
        /// <remarks>
        /// InstallationSettings is the site settings for an installation.
        /// </remarks>
        [JsonProperty(PropertyName = "installationSettings")]
        public IdjsonOKResponseInstallationSettings InstallationSettings { get; set; }

    }
}
