// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Teamwork.CRM.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Stage
    /// </summary>
    /// <remarks>
    /// Stage represents a stage in the CRM system.
    /// </remarks>
    public partial class IdjsonOKResponseStage
    {
        /// <summary>
        /// Initializes a new instance of the IdjsonOKResponseStage class.
        /// </summary>
        public IdjsonOKResponseStage()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the IdjsonOKResponseStage class.
        /// </summary>
        /// <param name="createdBy">[Resource identifier
        /// object](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#relationships)
        /// which describes a relationship to another entity.</param>
        /// <param name="deals">Deals related to the stage.</param>
        /// <param name="deletedBy">[Resource identifier
        /// object](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#relationships)
        /// which describes a relationship to another entity.</param>
        /// <param name="orderIndex">Position of the stage in the set of all
        /// stages in the system.
        /// Lower numbers come first when retrieving multiple elements at
        /// once.</param>
        /// <param name="pipeline">[Resource identifier
        /// object](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#relationships)
        /// which describes a relationship to another entity.</param>
        /// <param name="probability">A percentage that defines how much of the
        /// stage's value
        /// will be taken for the expected revenue in the forecast
        /// report.</param>
        /// <param name="updatedBy">[Resource identifier
        /// object](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#relationships)
        /// which describes a relationship to another entity.</param>
        public IdjsonOKResponseStage(System.DateTime? createdAt = default(System.DateTime?), IdjsonOKResponseStageCreatedBy createdBy = default(IdjsonOKResponseStageCreatedBy), IList<IdjsonOKResponseStageDealsItem> deals = default(IList<IdjsonOKResponseStageDealsItem>), int? dealsCount = default(int?), System.DateTime? deletedAt = default(System.DateTime?), IdjsonOKResponseStageDeletedBy deletedBy = default(IdjsonOKResponseStageDeletedBy), int? id = default(int?), string name = default(string), int? orderIndex = default(int?), IdjsonOKResponseStagePipeline pipeline = default(IdjsonOKResponseStagePipeline), int? probability = default(int?), System.DateTime? updatedAt = default(System.DateTime?), IdjsonOKResponseStageUpdatedBy updatedBy = default(IdjsonOKResponseStageUpdatedBy), int? updatedSourceId = default(int?))
        {
            CreatedAt = createdAt;
            CreatedBy = createdBy;
            Deals = deals;
            DealsCount = dealsCount;
            DeletedAt = deletedAt;
            DeletedBy = deletedBy;
            Id = id;
            Name = name;
            OrderIndex = orderIndex;
            Pipeline = pipeline;
            Probability = probability;
            UpdatedAt = updatedAt;
            UpdatedBy = updatedBy;
            UpdatedSourceId = updatedSourceId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "createdAt")]
        public System.DateTime? CreatedAt { get; set; }

        /// <summary>
        /// Gets or sets [Resource identifier
        /// object](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#relationships)
        /// which describes a relationship to another entity.
        /// </summary>
        [JsonProperty(PropertyName = "createdBy")]
        public IdjsonOKResponseStageCreatedBy CreatedBy { get; set; }

        /// <summary>
        /// Gets or sets deals related to the stage.
        /// </summary>
        [JsonProperty(PropertyName = "deals")]
        public IList<IdjsonOKResponseStageDealsItem> Deals { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dealsCount")]
        public int? DealsCount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "deletedAt")]
        public System.DateTime? DeletedAt { get; set; }

        /// <summary>
        /// Gets or sets [Resource identifier
        /// object](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#relationships)
        /// which describes a relationship to another entity.
        /// </summary>
        [JsonProperty(PropertyName = "deletedBy")]
        public IdjsonOKResponseStageDeletedBy DeletedBy { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets position of the stage in the set of all stages in the
        /// system.
        /// Lower numbers come first when retrieving multiple elements at once.
        /// </summary>
        [JsonProperty(PropertyName = "orderIndex")]
        public int? OrderIndex { get; set; }

        /// <summary>
        /// Gets or sets [Resource identifier
        /// object](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#relationships)
        /// which describes a relationship to another entity.
        /// </summary>
        [JsonProperty(PropertyName = "pipeline")]
        public IdjsonOKResponseStagePipeline Pipeline { get; set; }

        /// <summary>
        /// Gets or sets a percentage that defines how much of the stage's
        /// value
        /// will be taken for the expected revenue in the forecast report.
        /// </summary>
        [JsonProperty(PropertyName = "probability")]
        public int? Probability { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "updatedAt")]
        public System.DateTime? UpdatedAt { get; set; }

        /// <summary>
        /// Gets or sets [Resource identifier
        /// object](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#relationships)
        /// which describes a relationship to another entity.
        /// </summary>
        [JsonProperty(PropertyName = "updatedBy")]
        public IdjsonOKResponseStageUpdatedBy UpdatedBy { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "updatedSourceId")]
        public int? UpdatedSourceId { get; set; }

    }
}
