// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Teamwork.CRM.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// customFieldResponse
    /// </summary>
    public partial class IdjsonOKResponseModelModelModelModelModel
    {
        /// <summary>
        /// Initializes a new instance of the
        /// IdjsonOKResponseModelModelModelModelModel class.
        /// </summary>
        public IdjsonOKResponseModelModelModelModelModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// IdjsonOKResponseModelModelModelModelModel class.
        /// </summary>
        /// <param name="customField">CustomField</param>
        public IdjsonOKResponseModelModelModelModelModel(IdjsonOKResponseCustomField customField = default(IdjsonOKResponseCustomField))
        {
            CustomField = customField;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets customField
        /// </summary>
        /// <remarks>
        /// CustomField is a custom field defined by a user.
        /// </remarks>
        [JsonProperty(PropertyName = "customField")]
        public IdjsonOKResponseCustomField CustomField { get; set; }

    }
}
