// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Teamwork.CRM.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// stageResponse
    /// </summary>
    public partial class IdjsonOKResponseModelModelModelModelModelModelModelModelModelModelModelModelModel
    {
        /// <summary>
        /// Initializes a new instance of the
        /// IdjsonOKResponseModelModelModelModelModelModelModelModelModelModelModelModelModel
        /// class.
        /// </summary>
        public IdjsonOKResponseModelModelModelModelModelModelModelModelModelModelModelModelModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// IdjsonOKResponseModelModelModelModelModelModelModelModelModelModelModelModelModel
        /// class.
        /// </summary>
        /// <param name="included">Included</param>
        /// <param name="meta">stageGetMeta</param>
        /// <param name="stage">Stage</param>
        public IdjsonOKResponseModelModelModelModelModelModelModelModelModelModelModelModelModel(object included = default(object), IdjsonOKResponseMeta meta = default(IdjsonOKResponseMeta), IdjsonOKResponseStage stage = default(IdjsonOKResponseStage))
        {
            Included = included;
            Meta = meta;
            Stage = stage;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets included
        /// </summary>
        /// <remarks>
        /// Included contains all the side-loaded data of a response.
        /// See [including related
        /// entities](https://crmdev-teamwork.docs.stoplight.io/documentation/general/related-entities).
        /// </remarks>
        [JsonProperty(PropertyName = "included")]
        public object Included { get; set; }

        /// <summary>
        /// Gets or sets stageGetMeta
        /// </summary>
        [JsonProperty(PropertyName = "meta")]
        public IdjsonOKResponseMeta Meta { get; set; }

        /// <summary>
        /// Gets or sets stage
        /// </summary>
        /// <remarks>
        /// Stage represents a stage in the CRM system.
        /// </remarks>
        [JsonProperty(PropertyName = "stage")]
        public IdjsonOKResponseStage Stage { get; set; }

    }
}
