// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Teamwork.CRM.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// activityPositionResponse
    /// </summary>
    public partial class V1activityPositionResponse
    {
        /// <summary>
        /// Initializes a new instance of the V1activityPositionResponse class.
        /// </summary>
        public V1activityPositionResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the V1activityPositionResponse class.
        /// </summary>
        public V1activityPositionResponse(IList<V1activityPositionResponseActivitiesItem> activities = default(IList<V1activityPositionResponseActivitiesItem>))
        {
            Activities = activities;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "activities")]
        public IList<V1activityPositionResponseActivitiesItem> Activities { get; set; }

    }
}
