// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Teamwork.CRM.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// ActivityType
    /// </summary>
    /// <remarks>
    /// ActivityType represents an activity type in the CRM system.
    /// </remarks>
    public partial class V1activityTypesResponseActivityTypesItem
    {
        /// <summary>
        /// Initializes a new instance of the
        /// V1activityTypesResponseActivityTypesItem class.
        /// </summary>
        public V1activityTypesResponseActivityTypesItem()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// V1activityTypesResponseActivityTypesItem class.
        /// </summary>
        /// <param name="createdBy">[Resource identifier
        /// object](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#relationships)
        /// which describes a relationship to another entity.</param>
        /// <param name="deletedBy">[Resource identifier
        /// object](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#relationships)
        /// which describes a relationship to another entity.</param>
        /// <param name="icon">Icon of the activity type. Possible values
        /// include: 'clock', 'phone', 'suitcase', 'email', 'event',
        /// 'to-do'</param>
        /// <param name="orderIndex">Position of the activity type in the set
        /// of all enabled types.
        /// Lower numbers come first when retrieving multiple elements at
        /// once.</param>
        /// <param name="updatedBy">[Resource identifier
        /// object](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#relationships)
        /// which describes a relationship to another entity.</param>
        public V1activityTypesResponseActivityTypesItem(System.DateTime? createdAt = default(System.DateTime?), V1activityTypesResponseActivityTypesItemCreatedBy createdBy = default(V1activityTypesResponseActivityTypesItemCreatedBy), System.DateTime? deletedAt = default(System.DateTime?), V1activityTypesResponseActivityTypesItemDeletedBy deletedBy = default(V1activityTypesResponseActivityTypesItemDeletedBy), string icon = default(string), int? id = default(int?), bool? isEnabled = default(bool?), string name = default(string), int? orderIndex = default(int?), System.DateTime? updatedAt = default(System.DateTime?), V1activityTypesResponseActivityTypesItemUpdatedBy updatedBy = default(V1activityTypesResponseActivityTypesItemUpdatedBy), int? updatedSourceId = default(int?))
        {
            CreatedAt = createdAt;
            CreatedBy = createdBy;
            DeletedAt = deletedAt;
            DeletedBy = deletedBy;
            Icon = icon;
            Id = id;
            IsEnabled = isEnabled;
            Name = name;
            OrderIndex = orderIndex;
            UpdatedAt = updatedAt;
            UpdatedBy = updatedBy;
            UpdatedSourceId = updatedSourceId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "createdAt")]
        public System.DateTime? CreatedAt { get; set; }

        /// <summary>
        /// Gets or sets [Resource identifier
        /// object](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#relationships)
        /// which describes a relationship to another entity.
        /// </summary>
        [JsonProperty(PropertyName = "createdBy")]
        public V1activityTypesResponseActivityTypesItemCreatedBy CreatedBy { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "deletedAt")]
        public System.DateTime? DeletedAt { get; set; }

        /// <summary>
        /// Gets or sets [Resource identifier
        /// object](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#relationships)
        /// which describes a relationship to another entity.
        /// </summary>
        [JsonProperty(PropertyName = "deletedBy")]
        public V1activityTypesResponseActivityTypesItemDeletedBy DeletedBy { get; set; }

        /// <summary>
        /// Gets or sets icon of the activity type. Possible values include:
        /// 'clock', 'phone', 'suitcase', 'email', 'event', 'to-do'
        /// </summary>
        [JsonProperty(PropertyName = "icon")]
        public string Icon { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isEnabled")]
        public bool? IsEnabled { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets position of the activity type in the set of all
        /// enabled types.
        /// Lower numbers come first when retrieving multiple elements at once.
        /// </summary>
        [JsonProperty(PropertyName = "orderIndex")]
        public int? OrderIndex { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "updatedAt")]
        public System.DateTime? UpdatedAt { get; set; }

        /// <summary>
        /// Gets or sets [Resource identifier
        /// object](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#relationships)
        /// which describes a relationship to another entity.
        /// </summary>
        [JsonProperty(PropertyName = "updatedBy")]
        public V1activityTypesResponseActivityTypesItemUpdatedBy UpdatedBy { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "updatedSourceId")]
        public int? UpdatedSourceId { get; set; }

    }
}
