// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Teamwork.CRM.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Company
    /// </summary>
    /// <remarks>
    /// Company represents a company in the CRM system.
    /// </remarks>
    public partial class V1companiesResponseCompaniesItem
    {
        /// <summary>
        /// Initializes a new instance of the V1companiesResponseCompaniesItem
        /// class.
        /// </summary>
        public V1companiesResponseCompaniesItem()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the V1companiesResponseCompaniesItem
        /// class.
        /// </summary>
        /// <param name="avatar">[Resource identifier
        /// object](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#relationships)
        /// which describes a relationship to another entity.</param>
        /// <param name="contacts">[To-many relationship
        /// array](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#to-many-relationships)
        /// which describes a list of resource identifier objects.</param>
        /// <param name="contactsCount">Number of contacts connected.</param>
        /// <param name="country">[Resource identifier
        /// object](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#relationships)
        /// which describes a relationship to another entity.</param>
        /// <param name="createdBy">[Resource identifier
        /// object](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#relationships)
        /// which describes a relationship to another entity.</param>
        /// <param name="custom">Custom fields of the company.</param>
        /// <param name="deletedBy">[Resource identifier
        /// object](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#relationships)
        /// which describes a relationship to another entity.</param>
        /// <param name="owner">[Resource identifier
        /// object](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#relationships)
        /// which describes a relationship to another entity.</param>
        /// <param name="timezone">[Resource identifier
        /// object](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#relationships)
        /// which describes a relationship to another entity.</param>
        /// <param name="updatedBy">[Resource identifier
        /// object](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#relationships)
        /// which describes a relationship to another entity.</param>
        /// <param name="website">Companies website URL.</param>
        public V1companiesResponseCompaniesItem(string addressLine1 = default(string), string addressLine2 = default(string), V1companiesResponseCompaniesItemAvatar avatar = default(V1companiesResponseCompaniesItemAvatar), string city = default(string), IList<V1companiesResponseCompaniesItemContactsItem> contacts = default(IList<V1companiesResponseCompaniesItemContactsItem>), int? contactsCount = default(int?), V1companiesResponseCompaniesItemCountry country = default(V1companiesResponseCompaniesItemCountry), System.DateTime? createdAt = default(System.DateTime?), V1companiesResponseCompaniesItemCreatedBy createdBy = default(V1companiesResponseCompaniesItemCreatedBy), IList<V1companiesResponseCompaniesItemCustomItem> custom = default(IList<V1companiesResponseCompaniesItemCustomItem>), System.DateTime? deletedAt = default(System.DateTime?), V1companiesResponseCompaniesItemDeletedBy deletedBy = default(V1companiesResponseCompaniesItemDeletedBy), IList<V1companiesResponseCompaniesItemEmailAddressesItem> emailAddresses = default(IList<V1companiesResponseCompaniesItemEmailAddressesItem>), int? hubId = default(int?), int? id = default(int?), string name = default(string), V1companiesResponseCompaniesItemOwner owner = default(V1companiesResponseCompaniesItemOwner), V1companiesResponseCompaniesItemPhoneNumbers phoneNumbers = default(V1companiesResponseCompaniesItemPhoneNumbers), string stateOrCounty = default(string), V1companiesResponseCompaniesItemTimezone timezone = default(V1companiesResponseCompaniesItemTimezone), System.DateTime? updatedAt = default(System.DateTime?), V1companiesResponseCompaniesItemUpdatedBy updatedBy = default(V1companiesResponseCompaniesItemUpdatedBy), int? updatedSourceId = default(int?), string website = default(string), string zipcode = default(string))
        {
            AddressLine1 = addressLine1;
            AddressLine2 = addressLine2;
            Avatar = avatar;
            City = city;
            Contacts = contacts;
            ContactsCount = contactsCount;
            Country = country;
            CreatedAt = createdAt;
            CreatedBy = createdBy;
            Custom = custom;
            DeletedAt = deletedAt;
            DeletedBy = deletedBy;
            EmailAddresses = emailAddresses;
            HubId = hubId;
            Id = id;
            Name = name;
            Owner = owner;
            PhoneNumbers = phoneNumbers;
            StateOrCounty = stateOrCounty;
            Timezone = timezone;
            UpdatedAt = updatedAt;
            UpdatedBy = updatedBy;
            UpdatedSourceId = updatedSourceId;
            Website = website;
            Zipcode = zipcode;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "addressLine1")]
        public string AddressLine1 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "addressLine2")]
        public string AddressLine2 { get; set; }

        /// <summary>
        /// Gets or sets [Resource identifier
        /// object](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#relationships)
        /// which describes a relationship to another entity.
        /// </summary>
        [JsonProperty(PropertyName = "avatar")]
        public V1companiesResponseCompaniesItemAvatar Avatar { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "city")]
        public string City { get; set; }

        /// <summary>
        /// Gets or sets [To-many relationship
        /// array](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#to-many-relationships)
        /// which describes a list of resource identifier objects.
        /// </summary>
        [JsonProperty(PropertyName = "contacts")]
        public IList<V1companiesResponseCompaniesItemContactsItem> Contacts { get; set; }

        /// <summary>
        /// Gets or sets number of contacts connected.
        /// </summary>
        [JsonProperty(PropertyName = "contactsCount")]
        public int? ContactsCount { get; set; }

        /// <summary>
        /// Gets or sets [Resource identifier
        /// object](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#relationships)
        /// which describes a relationship to another entity.
        /// </summary>
        [JsonProperty(PropertyName = "country")]
        public V1companiesResponseCompaniesItemCountry Country { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "createdAt")]
        public System.DateTime? CreatedAt { get; set; }

        /// <summary>
        /// Gets or sets [Resource identifier
        /// object](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#relationships)
        /// which describes a relationship to another entity.
        /// </summary>
        [JsonProperty(PropertyName = "createdBy")]
        public V1companiesResponseCompaniesItemCreatedBy CreatedBy { get; set; }

        /// <summary>
        /// Gets or sets custom fields of the company.
        /// </summary>
        [JsonProperty(PropertyName = "custom")]
        public IList<V1companiesResponseCompaniesItemCustomItem> Custom { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "deletedAt")]
        public System.DateTime? DeletedAt { get; set; }

        /// <summary>
        /// Gets or sets [Resource identifier
        /// object](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#relationships)
        /// which describes a relationship to another entity.
        /// </summary>
        [JsonProperty(PropertyName = "deletedBy")]
        public V1companiesResponseCompaniesItemDeletedBy DeletedBy { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "emailAddresses")]
        public IList<V1companiesResponseCompaniesItemEmailAddressesItem> EmailAddresses { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "hubId")]
        public int? HubId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets [Resource identifier
        /// object](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#relationships)
        /// which describes a relationship to another entity.
        /// </summary>
        [JsonProperty(PropertyName = "owner")]
        public V1companiesResponseCompaniesItemOwner Owner { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "phoneNumbers")]
        public V1companiesResponseCompaniesItemPhoneNumbers PhoneNumbers { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "stateOrCounty")]
        public string StateOrCounty { get; set; }

        /// <summary>
        /// Gets or sets [Resource identifier
        /// object](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#relationships)
        /// which describes a relationship to another entity.
        /// </summary>
        [JsonProperty(PropertyName = "timezone")]
        public V1companiesResponseCompaniesItemTimezone Timezone { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "updatedAt")]
        public System.DateTime? UpdatedAt { get; set; }

        /// <summary>
        /// Gets or sets [Resource identifier
        /// object](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#relationships)
        /// which describes a relationship to another entity.
        /// </summary>
        [JsonProperty(PropertyName = "updatedBy")]
        public V1companiesResponseCompaniesItemUpdatedBy UpdatedBy { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "updatedSourceId")]
        public int? UpdatedSourceId { get; set; }

        /// <summary>
        /// Gets or sets companies website URL.
        /// </summary>
        [JsonProperty(PropertyName = "website")]
        public string Website { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "zipcode")]
        public string Zipcode { get; set; }

    }
}
