// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Teamwork.CRM.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// contactPositionResponse
    /// </summary>
    public partial class V1contactPositionResponse
    {
        /// <summary>
        /// Initializes a new instance of the V1contactPositionResponse class.
        /// </summary>
        public V1contactPositionResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the V1contactPositionResponse class.
        /// </summary>
        public V1contactPositionResponse(IList<V1contactPositionResponseContactsItem> contacts = default(IList<V1contactPositionResponseContactsItem>))
        {
            Contacts = contacts;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "contacts")]
        public IList<V1contactPositionResponseContactsItem> Contacts { get; set; }

    }
}
