// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Teamwork.CRM.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// companiesResponse
    /// </summary>
    public partial class V1companiesResponse
    {
        /// <summary>
        /// Initializes a new instance of the V1companiesResponse class.
        /// </summary>
        public V1companiesResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the V1companiesResponse class.
        /// </summary>
        /// <param name="included">Included</param>
        /// <param name="meta">ResponseMeta</param>
        public V1companiesResponse(IList<V1companiesResponseCompaniesItem> companies = default(IList<V1companiesResponseCompaniesItem>), object included = default(object), V1companiesResponseMeta meta = default(V1companiesResponseMeta))
        {
            Companies = companies;
            Included = included;
            Meta = meta;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "companies")]
        public IList<V1companiesResponseCompaniesItem> Companies { get; set; }

        /// <summary>
        /// Gets or sets included
        /// </summary>
        /// <remarks>
        /// Included contains all the side-loaded data of a response.
        /// See [including related
        /// entities](https://crmdev-teamwork.docs.stoplight.io/documentation/general/related-entities).
        /// </remarks>
        [JsonProperty(PropertyName = "included")]
        public object Included { get; set; }

        /// <summary>
        /// Gets or sets responseMeta
        /// </summary>
        /// <remarks>
        /// ResponseMeta contains common meta data.
        /// </remarks>
        [JsonProperty(PropertyName = "meta")]
        public V1companiesResponseMeta Meta { get; set; }

    }
}
