// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Teamwork.CRM.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class V1createCompanyRequestCompany
    {
        /// <summary>
        /// Initializes a new instance of the V1createCompanyRequestCompany
        /// class.
        /// </summary>
        public V1createCompanyRequestCompany()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the V1createCompanyRequestCompany
        /// class.
        /// </summary>
        /// <param name="contacts">[To-many relationship
        /// array](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#to-many-relationships)
        /// which describes a list of resource identifier objects.</param>
        /// <param name="country">[Resource identifier
        /// object](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#relationships)
        /// which describes a relationship to another entity.</param>
        /// <param name="custom">Custom fields of the entity, which properties
        /// are accepted in here will depend
        /// on your settings. For more information see
        /// [dealing with custom
        /// fields](https://crmdev-teamwork.docs.stoplight.io/documentation/miscellaneous/custom-fields).</param>
        /// <param name="owner">[Resource identifier
        /// object](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#relationships)
        /// which describes a relationship to another entity.</param>
        /// <param name="timezone">[Resource identifier
        /// object](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#relationships)
        /// which describes a relationship to another entity.</param>
        /// <param name="website">Companies website URL.</param>
        public V1createCompanyRequestCompany(string name, string addressLine1 = default(string), string addressLine2 = default(string), string city = default(string), IList<V1createCompanyRequestCompanyContactsItem> contacts = default(IList<V1createCompanyRequestCompanyContactsItem>), V1createCompanyRequestCompanyCountry country = default(V1createCompanyRequestCompanyCountry), object custom = default(object), IList<V1createCompanyRequestCompanyEmailAddressesItem> emailAddresses = default(IList<V1createCompanyRequestCompanyEmailAddressesItem>), V1createCompanyRequestCompanyOwner owner = default(V1createCompanyRequestCompanyOwner), V1createCompanyRequestCompanyPhoneNumbers phoneNumbers = default(V1createCompanyRequestCompanyPhoneNumbers), string stateOrCounty = default(string), V1createCompanyRequestCompanyTimezone timezone = default(V1createCompanyRequestCompanyTimezone), string website = default(string), string zipcode = default(string))
        {
            AddressLine1 = addressLine1;
            AddressLine2 = addressLine2;
            City = city;
            Contacts = contacts;
            Country = country;
            Custom = custom;
            EmailAddresses = emailAddresses;
            Name = name;
            Owner = owner;
            PhoneNumbers = phoneNumbers;
            StateOrCounty = stateOrCounty;
            Timezone = timezone;
            Website = website;
            Zipcode = zipcode;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "addressLine1")]
        public string AddressLine1 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "addressLine2")]
        public string AddressLine2 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "city")]
        public string City { get; set; }

        /// <summary>
        /// Gets or sets [To-many relationship
        /// array](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#to-many-relationships)
        /// which describes a list of resource identifier objects.
        /// </summary>
        [JsonProperty(PropertyName = "contacts")]
        public IList<V1createCompanyRequestCompanyContactsItem> Contacts { get; set; }

        /// <summary>
        /// Gets or sets [Resource identifier
        /// object](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#relationships)
        /// which describes a relationship to another entity.
        /// </summary>
        [JsonProperty(PropertyName = "country")]
        public V1createCompanyRequestCompanyCountry Country { get; set; }

        /// <summary>
        /// Gets or sets custom fields of the entity, which properties are
        /// accepted in here will depend
        /// on your settings. For more information see
        /// [dealing with custom
        /// fields](https://crmdev-teamwork.docs.stoplight.io/documentation/miscellaneous/custom-fields).
        /// </summary>
        [JsonProperty(PropertyName = "custom")]
        public object Custom { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "emailAddresses")]
        public IList<V1createCompanyRequestCompanyEmailAddressesItem> EmailAddresses { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets [Resource identifier
        /// object](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#relationships)
        /// which describes a relationship to another entity.
        /// </summary>
        [JsonProperty(PropertyName = "owner")]
        public V1createCompanyRequestCompanyOwner Owner { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "phoneNumbers")]
        public V1createCompanyRequestCompanyPhoneNumbers PhoneNumbers { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "stateOrCounty")]
        public string StateOrCounty { get; set; }

        /// <summary>
        /// Gets or sets [Resource identifier
        /// object](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#relationships)
        /// which describes a relationship to another entity.
        /// </summary>
        [JsonProperty(PropertyName = "timezone")]
        public V1createCompanyRequestCompanyTimezone Timezone { get; set; }

        /// <summary>
        /// Gets or sets companies website URL.
        /// </summary>
        [JsonProperty(PropertyName = "website")]
        public string Website { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "zipcode")]
        public string Zipcode { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Name == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Name");
            }
        }
    }
}
