// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Teamwork.CRM.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class V1createCustomFilterRequestCustomFilter
    {
        /// <summary>
        /// Initializes a new instance of the
        /// V1createCustomFilterRequestCustomFilter class.
        /// </summary>
        public V1createCustomFilterRequestCustomFilter()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// V1createCustomFilterRequestCustomFilter class.
        /// </summary>
        public V1createCustomFilterRequestCustomFilter(IList<V1createCustomFilterRequestCustomFilterColumnsItem> columns = default(IList<V1createCustomFilterRequestCustomFilterColumnsItem>), IList<V1createCustomFilterRequestCustomFilterConditionsItem> conditions = default(IList<V1createCustomFilterRequestCustomFilterConditionsItem>), string conditionsBinding = default(string), bool? isShared = default(bool?), string kind = default(string), string name = default(string), string orderBy = default(string), string orderMode = default(string))
        {
            Columns = columns;
            Conditions = conditions;
            ConditionsBinding = conditionsBinding;
            IsShared = isShared;
            Kind = kind;
            Name = name;
            OrderBy = orderBy;
            OrderMode = orderMode;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "columns")]
        public IList<V1createCustomFilterRequestCustomFilterColumnsItem> Columns { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "conditions")]
        public IList<V1createCustomFilterRequestCustomFilterConditionsItem> Conditions { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "conditionsBinding")]
        public string ConditionsBinding { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isShared")]
        public bool? IsShared { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "kind")]
        public string Kind { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "orderBy")]
        public string OrderBy { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "orderMode")]
        public string OrderMode { get; set; }

    }
}
