// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Teamwork.CRM.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class V1createCustomFieldRequestCustomField
    {
        /// <summary>
        /// Initializes a new instance of the
        /// V1createCustomFieldRequestCustomField class.
        /// </summary>
        public V1createCustomFieldRequestCustomField()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// V1createCustomFieldRequestCustomField class.
        /// </summary>
        /// <param name="fieldType">Type of the of the custom field value.
        /// Possible values include: 'text-short', 'text-long', 'number',
        /// 'select', 'multi-select', 'duration', 'url'</param>
        /// <param name="isMandatory">Mandatory is true if the custom field
        /// must have a value set, when the entity to which the custom field is
        /// assigned to, is created or updated.</param>
        /// <param name="isShownWhenAdding">Shown when adding is true when the
        /// custom field should be shown in the entity's form. Also, it must be
        /// true
        /// if the custom field is mandatory.</param>
        /// <param name="kind">Kind of entity this custom field is defined for.
        /// Possible values include: 'deals', 'contacts', 'companies'</param>
        /// <param name="options">Options for the custom field with `fieldType`
        /// "select" or "multi-select".</param>
        public V1createCustomFieldRequestCustomField(string fieldType, string name, bool? isMandatory = default(bool?), bool? isShownWhenAdding = default(bool?), string kind = default(string), IList<string> options = default(IList<string>))
        {
            FieldType = fieldType;
            IsMandatory = isMandatory;
            IsShownWhenAdding = isShownWhenAdding;
            Kind = kind;
            Name = name;
            Options = options;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets type of the of the custom field value. Possible values
        /// include: 'text-short', 'text-long', 'number', 'select',
        /// 'multi-select', 'duration', 'url'
        /// </summary>
        [JsonProperty(PropertyName = "fieldType")]
        public string FieldType { get; set; }

        /// <summary>
        /// Gets or sets mandatory is true if the custom field must have a
        /// value set, when the entity to which the custom field is
        /// assigned to, is created or updated.
        /// </summary>
        [JsonProperty(PropertyName = "isMandatory")]
        public bool? IsMandatory { get; set; }

        /// <summary>
        /// Gets or sets shown when adding is true when the custom field should
        /// be shown in the entity's form. Also, it must be true
        /// if the custom field is mandatory.
        /// </summary>
        [JsonProperty(PropertyName = "isShownWhenAdding")]
        public bool? IsShownWhenAdding { get; set; }

        /// <summary>
        /// Gets or sets kind of entity this custom field is defined for.
        /// Possible values include: 'deals', 'contacts', 'companies'
        /// </summary>
        [JsonProperty(PropertyName = "kind")]
        public string Kind { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets options for the custom field with `fieldType` "select"
        /// or "multi-select".
        /// </summary>
        [JsonProperty(PropertyName = "options")]
        public IList<string> Options { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (FieldType == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "FieldType");
            }
            if (Name == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Name");
            }
        }
    }
}
