// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Teamwork.CRM.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// createActivityRequest
    /// </summary>
    public partial class V1createActivityRequest
    {
        /// <summary>
        /// Initializes a new instance of the V1createActivityRequest class.
        /// </summary>
        public V1createActivityRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the V1createActivityRequest class.
        /// </summary>
        public V1createActivityRequest(V1createActivityRequestActivity activity)
        {
            Activity = activity;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "activity")]
        public V1createActivityRequestActivity Activity { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Activity == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Activity");
            }
            if (Activity != null)
            {
                Activity.Validate();
            }
        }
    }
}
