// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Teamwork.CRM.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// createExportRequest
    /// </summary>
    public partial class V1createExportRequest
    {
        /// <summary>
        /// Initializes a new instance of the V1createExportRequest class.
        /// </summary>
        public V1createExportRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the V1createExportRequest class.
        /// </summary>
        public V1createExportRequest(V1createExportRequestExport export = default(V1createExportRequestExport))
        {
            Export = export;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "export")]
        public V1createExportRequestExport Export { get; set; }

    }
}
