// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Teamwork.CRM.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class V1createStageRequestStage
    {
        /// <summary>
        /// Initializes a new instance of the V1createStageRequestStage class.
        /// </summary>
        public V1createStageRequestStage()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the V1createStageRequestStage class.
        /// </summary>
        /// <param name="orderIndex">Position of the stage in the set of all
        /// stages in the system.
        /// Lower numbers come first when retrieving multiple elements at
        /// once.</param>
        /// <param name="pipeline">[Resource identifier
        /// object](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#relationships)
        /// which describes a relationship to another entity.</param>
        /// <param name="probability">A percentage that defines how much of the
        /// stage's value
        /// will be taken for the expected revenue in the forecast
        /// report.</param>
        public V1createStageRequestStage(string name, int? orderIndex = default(int?), V1createStageRequestStagePipeline pipeline = default(V1createStageRequestStagePipeline), int? probability = default(int?))
        {
            Name = name;
            OrderIndex = orderIndex;
            Pipeline = pipeline;
            Probability = probability;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets position of the stage in the set of all stages in the
        /// system.
        /// Lower numbers come first when retrieving multiple elements at once.
        /// </summary>
        [JsonProperty(PropertyName = "orderIndex")]
        public int? OrderIndex { get; set; }

        /// <summary>
        /// Gets or sets [Resource identifier
        /// object](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#relationships)
        /// which describes a relationship to another entity.
        /// </summary>
        [JsonProperty(PropertyName = "pipeline")]
        public V1createStageRequestStagePipeline Pipeline { get; set; }

        /// <summary>
        /// Gets or sets a percentage that defines how much of the stage's
        /// value
        /// will be taken for the expected revenue in the forecast report.
        /// </summary>
        [JsonProperty(PropertyName = "probability")]
        public int? Probability { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Name == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Name");
            }
        }
    }
}
