// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Teamwork.CRM.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// createNote
    /// </summary>
    public partial class V1createNote
    {
        /// <summary>
        /// Initializes a new instance of the V1createNote class.
        /// </summary>
        public V1createNote()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the V1createNote class.
        /// </summary>
        /// <param name="subject">[Resource identifier
        /// object](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#relationships)
        /// which describes a relationship to another entity. Possible values
        /// include: 'deals', 'companies', 'contacts'</param>
        /// <param name="isPinned">Pinned is true when the note should appear
        /// immediately after the section in the UI in which you can create new
        /// notes.</param>
        public V1createNote(string description, string subject, bool? isPinned = default(bool?))
        {
            Description = description;
            IsPinned = isPinned;
            Subject = subject;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// Gets or sets pinned is true when the note should appear immediately
        /// after the section in the UI in which you can create new
        /// notes.
        /// </summary>
        [JsonProperty(PropertyName = "isPinned")]
        public bool? IsPinned { get; set; }

        /// <summary>
        /// Gets or sets [Resource identifier
        /// object](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#relationships)
        /// which describes a relationship to another entity. Possible values
        /// include: 'deals', 'companies', 'contacts'
        /// </summary>
        [JsonProperty(PropertyName = "subject")]
        public string Subject { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Description == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Description");
            }
            if (Subject == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Subject");
            }
        }
    }
}
