// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Teamwork.CRM.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// dealResponse
    /// </summary>
    public partial class V1dealResponse
    {
        /// <summary>
        /// Initializes a new instance of the V1dealResponse class.
        /// </summary>
        public V1dealResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the V1dealResponse class.
        /// </summary>
        /// <param name="deal">Deal</param>
        /// <param name="included">Included</param>
        public V1dealResponse(V1dealResponseDeal deal = default(V1dealResponseDeal), object included = default(object))
        {
            Deal = deal;
            Included = included;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets deal
        /// </summary>
        /// <remarks>
        /// Deal represents a deal in the CRM system.
        /// </remarks>
        [JsonProperty(PropertyName = "deal")]
        public V1dealResponseDeal Deal { get; set; }

        /// <summary>
        /// Gets or sets included
        /// </summary>
        /// <remarks>
        /// Included contains all the side-loaded data of a response.
        /// See [including related
        /// entities](https://crmdev-teamwork.docs.stoplight.io/documentation/general/related-entities).
        /// </remarks>
        [JsonProperty(PropertyName = "included")]
        public object Included { get; set; }

    }
}
