// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Teamwork.CRM.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// dealPositionResponse
    /// </summary>
    public partial class V1dealPositionResponse
    {
        /// <summary>
        /// Initializes a new instance of the V1dealPositionResponse class.
        /// </summary>
        public V1dealPositionResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the V1dealPositionResponse class.
        /// </summary>
        public V1dealPositionResponse(IList<V1dealPositionResponseDealsItem> deals = default(IList<V1dealPositionResponseDealsItem>))
        {
            Deals = deals;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "deals")]
        public IList<V1dealPositionResponseDealsItem> Deals { get; set; }

    }
}
