// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Teamwork.CRM.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// fileResponse
    /// </summary>
    public partial class V1fileResponse
    {
        /// <summary>
        /// Initializes a new instance of the V1fileResponse class.
        /// </summary>
        public V1fileResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the V1fileResponse class.
        /// </summary>
        /// <param name="file">File</param>
        public V1fileResponse(V1fileResponseFile file = default(V1fileResponseFile))
        {
            File = file;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets file
        /// </summary>
        /// <remarks>
        /// File represents a uploaded file in the CRM system.
        /// </remarks>
        [JsonProperty(PropertyName = "file")]
        public V1fileResponseFile File { get; set; }

    }
}
