// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Teamwork.CRM.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// LostReasonResponse
    /// </summary>
    /// <remarks>
    /// LostReasonResponse return a single lostReason,
    /// </remarks>
    public partial class V1LostReasonResponse
    {
        /// <summary>
        /// Initializes a new instance of the V1LostReasonResponse class.
        /// </summary>
        public V1LostReasonResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the V1LostReasonResponse class.
        /// </summary>
        /// <param name="lostReason">LostReason</param>
        public V1LostReasonResponse(V1LostReasonResponseLostReason lostReason = default(V1LostReasonResponseLostReason))
        {
            LostReason = lostReason;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets lostReason
        /// </summary>
        /// <remarks>
        /// LostReason represents a lost reason in the CRM system.
        /// </remarks>
        [JsonProperty(PropertyName = "lostReason")]
        public V1LostReasonResponseLostReason LostReason { get; set; }

    }
}
