// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Teamwork.CRM.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// meResponse
    /// </summary>
    public partial class V1meResponse
    {
        /// <summary>
        /// Initializes a new instance of the V1meResponse class.
        /// </summary>
        public V1meResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the V1meResponse class.
        /// </summary>
        /// <param name="included">Included</param>
        /// <param name="session">sessionResponse</param>
        public V1meResponse(object included = default(object), V1meResponseSession session = default(V1meResponseSession))
        {
            Included = included;
            Session = session;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets included
        /// </summary>
        /// <remarks>
        /// Included contains all the side-loaded data of a response.
        /// See [including related
        /// entities](https://crmdev-teamwork.docs.stoplight.io/documentation/general/related-entities).
        /// </remarks>
        [JsonProperty(PropertyName = "included")]
        public object Included { get; set; }

        /// <summary>
        /// Gets or sets sessionResponse
        /// </summary>
        [JsonProperty(PropertyName = "session")]
        public V1meResponseSession Session { get; set; }

    }
}
