// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Teamwork.CRM.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// noteResponse
    /// </summary>
    public partial class V1noteResponse
    {
        /// <summary>
        /// Initializes a new instance of the V1noteResponse class.
        /// </summary>
        public V1noteResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the V1noteResponse class.
        /// </summary>
        /// <param name="included">Included</param>
        /// <param name="note">Note</param>
        public V1noteResponse(object included = default(object), V1noteResponseNote note = default(V1noteResponseNote))
        {
            Included = included;
            Note = note;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets included
        /// </summary>
        /// <remarks>
        /// Included contains all the side-loaded data of a response.
        /// See [including related
        /// entities](https://crmdev-teamwork.docs.stoplight.io/documentation/general/related-entities).
        /// </remarks>
        [JsonProperty(PropertyName = "included")]
        public object Included { get; set; }

        /// <summary>
        /// Gets or sets note
        /// </summary>
        /// <remarks>
        /// Note represents a note in the CRM system.
        /// A Note can be related to one of Company, Contact or Deal.
        /// </remarks>
        [JsonProperty(PropertyName = "note")]
        public V1noteResponseNote Note { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Note != null)
            {
                Note.Validate();
            }
        }
    }
}
