// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Teamwork.CRM.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// patchContactRequest
    /// </summary>
    public partial class V1patchContactRequest
    {
        /// <summary>
        /// Initializes a new instance of the V1patchContactRequest class.
        /// </summary>
        public V1patchContactRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the V1patchContactRequest class.
        /// </summary>
        public V1patchContactRequest(V1patchContactRequestContact contact)
        {
            Contact = contact;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "contact")]
        public V1patchContactRequestContact Contact { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Contact == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Contact");
            }
        }
    }
}
