// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Teamwork.CRM.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class V1PatchPipelineRequestPipeline
    {
        /// <summary>
        /// Initializes a new instance of the V1PatchPipelineRequestPipeline
        /// class.
        /// </summary>
        public V1PatchPipelineRequestPipeline()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the V1PatchPipelineRequestPipeline
        /// class.
        /// </summary>
        /// <param name="orderIndex">Position of the pipeline in the set of all
        /// pipelines.
        /// Lower numbers come first when retrieving multiple elements at
        /// once.</param>
        public V1PatchPipelineRequestPipeline(string name = default(string), int? orderIndex = default(int?))
        {
            Name = name;
            OrderIndex = orderIndex;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets position of the pipeline in the set of all pipelines.
        /// Lower numbers come first when retrieving multiple elements at once.
        /// </summary>
        [JsonProperty(PropertyName = "orderIndex")]
        public int? OrderIndex { get; set; }

    }
}
