// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Teamwork.CRM.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// patchCompanyRequest
    /// </summary>
    public partial class V1patchCompanyRequest
    {
        /// <summary>
        /// Initializes a new instance of the V1patchCompanyRequest class.
        /// </summary>
        public V1patchCompanyRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the V1patchCompanyRequest class.
        /// </summary>
        public V1patchCompanyRequest(V1patchCompanyRequestCompany company)
        {
            Company = company;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "company")]
        public V1patchCompanyRequestCompany Company { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Company == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Company");
            }
        }
    }
}
