// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Teamwork.CRM.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// [Resource identifier
    /// object](https://crmdev-teamwork.docs.stoplight.io/documentation/general/entity-models#relationships)
    /// linking to a currency.
    /// This currency will be used when converting multiple currencies to one,
    /// e.g deals totalValue
    /// field.
    /// </summary>
    public partial class V1patchInstallationSettingsRequestInstallationSettingsCurrency
    {
        /// <summary>
        /// Initializes a new instance of the
        /// V1patchInstallationSettingsRequestInstallationSettingsCurrency
        /// class.
        /// </summary>
        public V1patchInstallationSettingsRequestInstallationSettingsCurrency()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// V1patchInstallationSettingsRequestInstallationSettingsCurrency
        /// class.
        /// </summary>
        /// <param name="id">The id of the currency.</param>
        /// <param name="type">Possible values include: 'currencies'</param>
        public V1patchInstallationSettingsRequestInstallationSettingsCurrency(int? id = default(int?), string type = default(string))
        {
            Id = id;
            Type = type;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the id of the currency.
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int? Id { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'currencies'
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public string Type { get; set; }

    }
}
