// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Teamwork.CRM.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// pipelineBoardResponse
    /// </summary>
    public partial class V1pipelineBoardResponse
    {
        /// <summary>
        /// Initializes a new instance of the V1pipelineBoardResponse class.
        /// </summary>
        public V1pipelineBoardResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the V1pipelineBoardResponse class.
        /// </summary>
        /// <param name="included">Included</param>
        /// <param name="meta">pipelineBoardMetaResponse</param>
        /// <param name="pipeline">Pipeline</param>
        public V1pipelineBoardResponse(object included = default(object), V1pipelineBoardResponseMeta meta = default(V1pipelineBoardResponseMeta), V1pipelineBoardResponsePipeline pipeline = default(V1pipelineBoardResponsePipeline))
        {
            Included = included;
            Meta = meta;
            Pipeline = pipeline;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets included
        /// </summary>
        /// <remarks>
        /// Included contains all the side-loaded data of a response.
        /// See [including related
        /// entities](https://crmdev-teamwork.docs.stoplight.io/documentation/general/related-entities).
        /// </remarks>
        [JsonProperty(PropertyName = "included")]
        public object Included { get; set; }

        /// <summary>
        /// Gets or sets pipelineBoardMetaResponse
        /// </summary>
        [JsonProperty(PropertyName = "meta")]
        public V1pipelineBoardResponseMeta Meta { get; set; }

        /// <summary>
        /// Gets or sets pipeline
        /// </summary>
        /// <remarks>
        /// Pipeline represents a pipeline in the CRM system.
        /// </remarks>
        [JsonProperty(PropertyName = "pipeline")]
        public V1pipelineBoardResponsePipeline Pipeline { get; set; }

    }
}
