// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Teamwork.CRM.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// pipelineBoardMetaResponse
    /// </summary>
    public partial class V1pipelineBoardMetaResponse
    {
        /// <summary>
        /// Initializes a new instance of the V1pipelineBoardMetaResponse
        /// class.
        /// </summary>
        public V1pipelineBoardMetaResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the V1pipelineBoardMetaResponse
        /// class.
        /// </summary>
        public V1pipelineBoardMetaResponse(int? maxStageDealsCount = default(int?), object stagesTotalValues = default(object))
        {
            MaxStageDealsCount = maxStageDealsCount;
            StagesTotalValues = stagesTotalValues;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "maxStageDealsCount")]
        public int? MaxStageDealsCount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "stagesTotalValues")]
        public object StagesTotalValues { get; set; }

    }
}
