// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Teamwork.CRM.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// stageGetMeta
    /// </summary>
    public partial class V1stageGetMeta
    {
        /// <summary>
        /// Initializes a new instance of the V1stageGetMeta class.
        /// </summary>
        public V1stageGetMeta()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the V1stageGetMeta class.
        /// </summary>
        /// <param name="totalValue">Total value of the stage in your currency
        /// in its lowest denomination,
        /// e.g for USD the value in cents. This is the customValue of
        /// all the deals in the stage (ignoring pagination) plus the sum
        /// of all the deals products prices.</param>
        public V1stageGetMeta(double? totalValue = default(double?))
        {
            TotalValue = totalValue;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets total value of the stage in your currency in its
        /// lowest denomination,
        /// e.g for USD the value in cents. This is the customValue of
        /// all the deals in the stage (ignoring pagination) plus the sum
        /// of all the deals products prices.
        /// </summary>
        [JsonProperty(PropertyName = "totalValue")]
        public double? TotalValue { get; set; }

    }
}
