// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Teamwork.CRM.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Phone
    /// </summary>
    /// <remarks>
    /// Phone entity description
    /// </remarks>
    public partial class V1usersResponseUsersItemPhoneNumbersItem
    {
        /// <summary>
        /// Initializes a new instance of the
        /// V1usersResponseUsersItemPhoneNumbersItem class.
        /// </summary>
        public V1usersResponseUsersItemPhoneNumbersItem()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// V1usersResponseUsersItemPhoneNumbersItem class.
        /// </summary>
        /// <param name="code">ResourceIdentifier</param>
        public V1usersResponseUsersItemPhoneNumbersItem(V1usersResponseUsersItemPhoneNumbersItemCode code = default(V1usersResponseUsersItemPhoneNumbersItemCode), int? hubId = default(int?), bool? isMain = default(bool?), string number = default(string))
        {
            Code = code;
            HubId = hubId;
            IsMain = isMain;
            Number = number;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets resourceIdentifier
        /// </summary>
        /// <remarks>
        /// ResourceIdentifier identifies a relationship resource.
        /// </remarks>
        [JsonProperty(PropertyName = "code")]
        public V1usersResponseUsersItemPhoneNumbersItemCode Code { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "hubId")]
        public int? HubId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isMain")]
        public bool? IsMain { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "number")]
        public string Number { get; set; }

    }
}
